version: "3.5"

services:
  pgsql:
    image: postgres:12
    environment:
      POSTGRES_HOST: 'pgsql'
      POSTGRES_USER: 'django'
      POSTGRES_PASSWORD: 'hotelrooms'
      POSTGRES_DB: 'hotelrooms'
    volumes:
      - data-postgresql:/var/lib/postgresql
    ports:
      - "5434:5432"
  django:
    build: .
    depends_on:
      - pgsql
    environment:
      DB_HOST: pgsql
      DB_PORT: 5434
    ports:
      - "8000:8000"
    volumes:
      - media:/usr/web/app # for images etc.

volumes:
  data-postgresql:
  media:
