# Generated by Django 3.0.7 on 2020-06-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('floor', 'no')},
        ),
    ]
